name: Publish
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - run: npm install
      - run: npm run build
      - run: |
          echo @ytoyodadev:https://npm.pkg.github.com/ > .npmrc
          echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN_CODEGEN}' >> .npmrc
      - run: npm publish
        env:
          NPM_TOKEN_CODEGEN: ${{ secrets.GITHUB_TOKEN }}
